---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    collections-path: ~/.ansible/collections

driver:
  name: vagrant

platforms:
  - name: ubuntu-instance
    box: ubuntu/focal64
    instance_raw_config_args:
      - "vm.network 'private_network', type: 'dhcp'"

scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge